<a href="https://colab.research.google.com/github/NipunRaj96/DeepLearning/blob/main/One_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
#Creating Encoder
enc=OneHotEncoder(handle_unknown='ignore')
enc1=OneHotEncoder(handle_unknown='ignore')
# Sample data
X=[['Red'],['Green'],['Blue']] #change word length
Y = [['good boy'],['boy bad'],['girl']]
#fitting encoder to the data
enc.fit(X)
enc1.fit(Y)
result = enc.transform(X).toarray()
result1 = enc1.transform(Y).toarray()
print(result)
print(result1)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [14]:
sentences = [
    "this is an example sentence",
    "Here's another sentence for demo",
    "and yet another one"
]
words=[]
for sentence in sentences:
  words.extend(sentence.split())
data = np.array(words).reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
encoded_data = encoder.fit_transform(data)
print(encoded_data)
print(encoder.categories_)

# Create a copy of the array before reshaping to avoid modifying a read-only array
data2 = np.array(np.unique(data)).reshape((-1,1)).copy()
encoded_data2 = encoder.fit_transform(data2)
print(encoded_data2)
print(np.unique(data))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[array(["Here's", 'an', 'and', 'another', 'demo', 'example', 'for', 'is',
       'one', 'sentence', 'this', 'yet'], dtype='<U8')]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 